"""add_image_fields_and_reddit_comments

Revision ID: 29eabc573f64
Revises: af5623681ffd
Create Date: 2026-06-16 18:35:45.531100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29eabc573f64'
down_revision: Union[str, None] = 'af5623681ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.String(length=128), nullable=False),
    sa.Column('reddit_post_id', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('permalink', sa.String(length=2048), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_comments_article_id'), 'reddit_comments', ['article_id'], unique=False)
    op.add_column('articles', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('articles', sa.Column('image_url_original', sa.String(length=2048), nullable=True))
    op.add_column('articles', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('articles', sa.Column('reddit_post_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'reddit_post_id')
    op.drop_column('articles', 'is_featured')
    op.drop_column('articles', 'image_url_original')
    op.drop_column('articles', 'image_url')
    op.drop_index(op.f('ix_reddit_comments_article_id'), table_name='reddit_comments')
    op.drop_table('reddit_comments')
    # ### end Alembic commands ###
