"""Change article id to string

Revision ID: c518d981f0e1
Revises: f1479d487868
Create Date: 2026-06-14 19:32:49.448509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c518d981f0e1'
down_revision: Union[str, None] = 'f1479d487868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'id',
               existing_type=sa.String(length=128),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
