"""add ingestion_runs table

Revision ID: ceaa147db0ee
Revises: 7e4e00abaaa8
Create Date: 2026-06-20 20:28:56.283785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceaa147db0ee'
down_revision: Union[str, None] = '7e4e00abaaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
